<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Information</name>
   <tag></tag>
   <elementGuidId>3e67f21a-7832-44aa-8688-851ddb2209a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-3.rounded.border-n-20.d-flex.mb-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div[2]/div/div/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>CartItem-Card</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-3 rounded border-n-20 d-flex mb-3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Metode: UploadScreenshot%2520%2825%29.pngLabel Stiker Kemasan Satuan (Die Cut)25 pcsRp 56.500See SpecificationsDuplicate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;py-md-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;pt-2 pt-sm-0 col-md-8 col-12&quot;]/div[@class=&quot;mb-4 css-ebxke4-CartCard card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;p-3 rounded border-n-20 d-flex mb-3&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div[2]/div/div/div[2]/div[2]/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 0'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Cost'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Metode: UploadScreenshot%2520%2825%29.pngLabel Stiker Kemasan Satuan (Die Cut)25 pcsRp 56.500See SpecificationsDuplicate' or . = 'Metode: UploadScreenshot%2520%2825%29.pngLabel Stiker Kemasan Satuan (Die Cut)25 pcsRp 56.500See SpecificationsDuplicate')]</value>
   </webElementXpaths>
</WebElementEntity>
